import type { CodegenPlugin } from "../types.js";

/**
 * Reference transpiler: PineScript v5/v6 → NinjaScript 8 (C#).
 *
 * This is intentionally minimal — a viable starting skeleton, not a full
 * Pine compiler. It handles:
 *   - indicator() / strategy() metadata
 *   - simple input() declarations
 *   - the most common built-ins (ta.rsi, ta.sma, ta.ema, ta.crossover, ta.crossunder)
 *   - plot() → AddPlot in OnStateChange + Values[0] assignment in OnBarUpdate
 *
 * For production-grade Pine→NT8 codegen plug a richer engine (e.g. TradeScript
 * AI) by registering its own CodegenPlugin. This in-tree plugin exists so the
 * MCP returns something useful out-of-the-box.
 */

interface PineInput {
  name: string;
  defaultValue: string;
  type: "int" | "float" | "bool" | "string";
}

function detectInputs(source: string): PineInput[] {
  const inputs: PineInput[] = [];
  const re = /input(?:\.(int|float|bool|string))?\(\s*([^,)]+)(?:,\s*"([^"]+)")?/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source)) !== null) {
    const type = (m[1] as PineInput["type"]) ?? "float";
    const defaultValue = (m[2] ?? "0").trim();
    const name = (m[3] ?? `input${inputs.length + 1}`).replace(/\s+/g, "_");
    inputs.push({ name, defaultValue, type });
  }
  return inputs;
}

function detectStrategyMode(source: string): boolean {
  return /^\s*strategy\(/m.test(source) || /strategy\.entry|strategy\.exit/.test(source);
}

function pineTypeToCs(t: PineInput["type"]): string {
  switch (t) {
    case "int":
      return "int";
    case "float":
      return "double";
    case "bool":
      return "bool";
    case "string":
      return "string";
  }
}

function translateBody(source: string): string[] {
  const lines: string[] = [];
  // Very small mapping. The point is to show wiring; richer rewrites land in
  // downstream codegen plugins.
  const ohlc: Record<string, string> = {
    close: "Close[0]",
    open: "Open[0]",
    high: "High[0]",
    low: "Low[0]",
    volume: "Volume[0]",
  };
  for (const line of source.split(/\r?\n/)) {
    const t = line.trim();
    if (!t || t.startsWith("//")) continue;
    let cs = t
      .replace(/\bta\.rsi\(([^,]+),\s*(\d+)\)/g, (_m, src, len) => `RSI(${ohlc[src.trim()] ?? src}, ${len})[0]`)
      .replace(/\bta\.sma\(([^,]+),\s*(\d+)\)/g, (_m, src, len) => `SMA(${ohlc[src.trim()] ?? src}, ${len})[0]`)
      .replace(/\bta\.ema\(([^,]+),\s*(\d+)\)/g, (_m, src, len) => `EMA(${ohlc[src.trim()] ?? src}, ${len})[0]`)
      .replace(/\bta\.crossover\(([^,]+),\s*([^)]+)\)/g, (_m, a, b) => `(${a.trim()} > ${b.trim()} && ${a.trim()}[1] <= ${b.trim()}[1])`)
      .replace(/\bta\.crossunder\(([^,]+),\s*([^)]+)\)/g, (_m, a, b) => `(${a.trim()} < ${b.trim()} && ${a.trim()}[1] >= ${b.trim()}[1])`);
    for (const [k, v] of Object.entries(ohlc)) {
      cs = cs.replace(new RegExp(`\\b${k}\\b`, "g"), v);
    }
    lines.push(`// pine: ${t}`);
    lines.push(`// nt8:  ${cs}`);
  }
  return lines;
}

export function createPineToNt8Plugin(): CodegenPlugin {
  return {
    name: "pine-to-nt8",
    kind: "codegen",
    source_languages: ["pinescript"],
    target_languages: ["ninjascript"],

    async transpile({ source, from, to }) {
      if (from !== "pinescript" || to !== "ninjascript") {
        throw new Error(`pine-to-nt8 only transpiles pinescript → ninjascript; got ${from} → ${to}`);
      }
      const warnings: string[] = [];
      const isStrategy = detectStrategyMode(source);
      const inputs = detectInputs(source);
      const className = "TradeStackStrategy";
      const baseClass = isStrategy ? "Strategy" : "Indicator";

      const inputDecls = inputs
        .map((i) => `[NinjaScriptProperty]\n    public ${pineTypeToCs(i.type)} ${i.name} { get; set; } = ${i.defaultValue};`)
        .join("\n\n    ");

      const bodyLines = translateBody(source);
      if (bodyLines.length === 0) warnings.push("source produced no translated body lines");

      const code = `
// Generated by TradeStack MCP pine-to-nt8 plugin
// Source language: pinescript / Target language: ninjascript
using NinjaTrader.NinjaScript.${isStrategy ? "Strategies" : "Indicators"};
using NinjaTrader.NinjaScript.Indicators;
using NinjaTrader.Cbi;

namespace NinjaTrader.NinjaScript.${isStrategy ? "Strategies" : "Indicators"}
{
  public class ${className} : ${baseClass}
  {
    ${inputDecls || "// no inputs detected"}

    protected override void OnStateChange()
    {
      if (State == State.SetDefaults)
      {
        Name = "${className}";
        IsOverlay = false;
      }
    }

    protected override void OnBarUpdate()
    {
      if (CurrentBar < 1) return;
      // ───────── Pine→NT8 translated body (alpha) ─────────
      ${bodyLines.join("\n      ")}
    }
  }
}
`.trim();

      return { code, warnings };
    },

    async validate({ code, language }) {
      if (language !== "ninjascript") {
        return { ok: false, errors: [{ message: `validate() unsupported for language=${language}` }] };
      }
      // Static check: look for the most common hallucinated NT8 properties
      // (see VZT memory: feedback_nt8_hallucinated_props).
      const banned = ["ExitOnSessionClose", "MaxDrawdown ", "AllowSelectionOnHistorical "];
      const errors: Array<{ line: number; message: string }> = [];
      code.split(/\r?\n/).forEach((line, idx) => {
        for (const b of banned) {
          if (line.includes(b)) {
            errors.push({ line: idx + 1, message: `Hallucinated NT8 property: ${b.trim()}` });
          }
        }
      });
      return { ok: errors.length === 0, errors };
    },
  };
}
